import axios from "axios";

export default async function getAllDepartmentsByCity(city, page) {
    const baseURL = import.meta.env.VITE_BASE_URL;

    if (!city || city === "" || !page || page === "") {
        return [];
    } else
        if (baseURL === "/api") {
        const res = await axios.post(baseURL + "/nova/poshta/get/departments", {Ref: city, page: page});
        return res.data;
    } else {
        return [
            { Ref: "1", Description: "аа" },
            { Ref: "2", Description: "аа" },
            { Ref: "3", Description: "аа" },
            { Ref: "4", Description: "аа" },
            { Ref: "5", Description: "аа" },
            { Ref: "6", Description: "аа" },
            { Ref: "7", Description: "аа" },
            { Ref: "8", Description: "аа" },
            { Ref: "9", Description: "аа" },
            { Ref: "10", Description: "аа" },
            { Ref: "11", Description: "аа" },
            { Ref: "12", Description: "аа" },
            { Ref: "13", Description: "аа" },
            { Ref: "14", Description: "аа" },
            { Ref: "15", Description: "аа" },
            { Ref: "16", Description: "аа" },
            { Ref: "17", Description: "аа" },
            { Ref: "18", Description: "аа" },
            { Ref: "19", Description: "аа" },
            { Ref: "20", Description: "аа" },
            { Ref: "21", Description: "аа" },
            { Ref: "22", Description: "аа" },
            { Ref: "23", Description: "аа" },
            { Ref: "24", Description: "аа" },
            { Ref: "25", Description: "аа" },
            { Ref: "26", Description: "аа" },
            { Ref: "27", Description: "аа" },
            { Ref: "28", Description: "аа" },
            { Ref: "29", Description: "аа" },
            { Ref: "30", Description: "аа" },
            { Ref: "31", Description: "аа" },
            { Ref: "32", Description: "аа" },
            { Ref: "33", Description: "аа" },
            { Ref: "34", Description: "аа" },
            { Ref: "35", Description: "аа" },
            { Ref: "36", Description: "аа" },
            { Ref: "37", Description: "аа" },
            { Ref: "38", Description: "аа" },
            { Ref: "39", Description: "аа" },
            { Ref: "40", Description: "аа" },
            { Ref: "41", Description: "аа" },
            { Ref: "42", Description: "аа" },
            { Ref: "43", Description: "аа" },
            { Ref: "44", Description: "аа" },
            { Ref: "45", Description: "аа" },
            { Ref: "46", Description: "аа" },
            { Ref: "47", Description: "аа" },
            { Ref: "48", Description: "аа" },
            { Ref: "49", Description: "аа" },
            { Ref: "50", Description: "аа" },
            { Ref: "51", Description: "аа" },
            { Ref: "52", Description: "аа" },
            { Ref: "53", Description: "аа" },
            { Ref: "54", Description: "аа" },
            { Ref: "55", Description: "аа" },
            { Ref: "56", Description: "аа" },
            { Ref: "57", Description: "аа" },
            { Ref: "58", Description: "аа" },
            { Ref: "59", Description: "аа" },
            { Ref: "60", Description: "аа" },
            { Ref: "61", Description: "аа" },
            { Ref: "62", Description: "аа" },
            { Ref: "63", Description: "аа" },
            { Ref: "64", Description: "аа" },
            { Ref: "65", Description: "аа" },
            { Ref: "66", Description: "аа" },
            { Ref: "67", Description: "аа" },
            { Ref: "68", Description: "аа" },
            { Ref: "69", Description: "аа" },
            { Ref: "70", Description: "аа" },
            { Ref: "71", Description: "аа" },
            { Ref: "72", Description: "аа" },
            { Ref: "73", Description: "аа" },
            { Ref: "74", Description: "аа" },
            { Ref: "75", Description: "аа" },
            { Ref: "76", Description: "аа" },
            { Ref: "77", Description: "аа" },
            { Ref: "78", Description: "аа" },
            { Ref: "79", Description: "аа" },
            { Ref: "80", Description: "аа" },
            { Ref: "81", Description: "аа" },
            { Ref: "82", Description: "аа" },
            { Ref: "83", Description: "аа" },
            { Ref: "84", Description: "аа" },
            { Ref: "85", Description: "аа" },
            { Ref: "86", Description: "аа" },
            { Ref: "87", Description: "аа" },
            { Ref: "88", Description: "аа" },
            { Ref: "89", Description: "аа" },
            { Ref: "90", Description: "аа" },
            { Ref: "91", Description: "аа" },
            { Ref: "92", Description: "аа" },
            { Ref: "93", Description: "аа" },
            { Ref: "94", Description: "аа" },
            { Ref: "95", Description: "аа" },
            { Ref: "96", Description: "аа" },
            { Ref: "97", Description: "аа" },
            { Ref: "98", Description: "аа" },
            { Ref: "99", Description: "аа" },
            { Ref: "100", Description: "аа" },
            { Ref: "101", Description: "аа" }
        ];
    }
}